version: '3.6'

services:

  shortener.nginx:
    build:
      context: ./docker/nginx
    container_name: shortener.nginx
    env_file:
      - ./docker/.env
    ports:
      - "80:80"
    links:
      - shortener.php
    volumes:
      - ./public:/var/www/shortener/public
    networks:
      - shortener_network

  shortener.php:
    build:
      context: ./docker/php
    container_name: shortener.php
    env_file:
      - ./docker/.env
    expose:
      - 9000
    volumes:
      - ./:/var/www/shortener:rw
    networks:
      - shortener_network

  shortener.db:
    image: postgres:${POSTGRES_VERSION:-14}
    container_name: shortener.db
    env_file:
      - ./docker/.env
    ports:
      - "5432:5432"
    volumes:
      - ./docker/var/db-data:/var/lib/postgresql/data:rw
    networks:
      - shortener_network

volumes:
  db-data:

networks:
  shortener_network:
    driver: bridge